server:
  port: 8099
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:10001/eureka/
    register-with-eureka: true # 当前的微服务不注册到eureka之中
    fetch-registry: true # 不通过eureka获取注册信息
spring:
  application:
    name: sms-server