server:
  port: 8002

mybatis:
  config-location: classpath:mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: cn.ddw.apiService.goodsService.entity   # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: goodsService-Impl
  datasource:
    druid:
      test-on-borrow: true
      test-while-idle: true
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://106.13.73.110:3306/ddw              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间



eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:10001/eureka